apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
  namespace: linkding
data:
  config.yaml: |
    tunnel: linkding
    credentials-file: /etc/cloudflared/creds/credentials.json

    no-autoupdate: true
    ingress:
    - hostname: linkding.eniohomelab.com
      service: http://linkding:80
    - service: http_status:404