apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 9Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
