apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: |
    tunnel: trilium
    credentials-file: /etc/cloudflared/creds/credentials.json

    no-autoupdate: true
    ingress:
    - hostname: trilium.eniohomelab.com
      service: http://trilium:80
    - service: http_status:404