apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homarr
resources:
  - homarr-container-env-secret.yaml
  - cloudflared-configmap.yaml
  - cloudflared-deployment.yaml
  - cloudflared-creds-secret.yaml
  - ../../base/homarr/