apiVersion: v1
data:
    ACCESS_KEY: ENC[AES256_GCM,data:2dO0E2qbdI6HNl4o3McOCqWXET7o09o7bWCywdWkO9//OqZbV00WdkRHAeU=,iv:jkfMacQ3NFiAI8ManfquuWRQQdn2hokXN6wu4wWYyx8=,tag:TQoA4tAPQ5y9dNUiVcFGPw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:9yE11HYZB5aLGGDYVltVvpURl9FBGDEfa1FCnfX6tkqOpOPW0CITTMCkQOwuQEWqVU3MKpHZFyHuaM6+8zZb0Cigrw5McwyPdV2XFwm/a6dSZtUqbVj3nA==,iv:QUeNTGAPLwSUGnGh5qLe4nxgCRIRcPNKfacHlyIT6d0=,tag:5umOqaLcKEGMXE6y/LAG3Q==,type:str]
kind: Secret
metadata:
    name: passbolt-db-production-backup-s3-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucTFabXNKSXBOeTdTY2F5
            YWdib2ZORE12Z3cyaUNWKzJuNER2eUl1a1RjClZObUJsdWtuV2VBby9ub0dZcFlO
            MzU3ZlA5Wll3Qk5VK2x6YVdOL293d0kKLS0tIHpKNHJaaVF3VzduUHhQSzlDOE5J
            YnRwRjJpQThyamxGNzB5WXN1N3dWNEUKG8MxSneWbCVYoXHcS3rDC0XXquUQs3IJ
            IHQNGkdRNst/sxBSU0p4atXqsUR2xtmyJfHH179xwACDOLOdY/LL6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T00:20:55Z"
    mac: ENC[AES256_GCM,data:VdGlR3g5FMi7mCQW9gXDy/ZB3zx37eF4k4l6k1uoevzsAApwZ3K7JIXj8y9zfxZaUJs6mLdog2JwPLQn3u/25qvY3agm9OoRfb3x51TFuYmhMrH7sLwbcDKPPR4mVkUGlCBOgfKfQ2KpxtKeaQXLXplgrRRvaUYkq+9cYUSHaFY=,iv:aBMFg2t0IUQVuyvJp40xLQYlkBRr+6CZkN78Mo36QdI=,tag:MZbl24l4Zgs9Xm7zK2kC6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TwOvdEDLNw7tniciuvpVN6btUr2CnuKLvEvoQIbcLIx1qnRY7mNUm2hVzaRHH17FSddcdC4i8XhFGCU74NeURni6QQ/0tIKtBxT0zQB6SPBn7SVxwtNoWA==,iv:J4n+a79kGGta4Y0d5v2nxRwET+tXffBEIeDaCcm9/6A=,tag:N+H7f2anR0KbKfHUWa9ESA==,type:str]
    username: ENC[AES256_GCM,data:fFeXZA==,iv:oaj+llwWMZOoUDLilSZZWihZfD1yYbXqFQxCMzcDU4w=,tag:gE5dXAj9ZbOUrLTzS9Isrg==,type:str]
kind: Secret
metadata:
    name: passbolt-db-creds
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucTFabXNKSXBOeTdTY2F5
            YWdib2ZORE12Z3cyaUNWKzJuNER2eUl1a1RjClZObUJsdWtuV2VBby9ub0dZcFlO
            MzU3ZlA5Wll3Qk5VK2x6YVdOL293d0kKLS0tIHpKNHJaaVF3VzduUHhQSzlDOE5J
            YnRwRjJpQThyamxGNzB5WXN1N3dWNEUKG8MxSneWbCVYoXHcS3rDC0XXquUQs3IJ
            IHQNGkdRNst/sxBSU0p4atXqsUR2xtmyJfHH179xwACDOLOdY/LL6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T00:20:55Z"
    mac: ENC[AES256_GCM,data:VdGlR3g5FMi7mCQW9gXDy/ZB3zx37eF4k4l6k1uoevzsAApwZ3K7JIXj8y9zfxZaUJs6mLdog2JwPLQn3u/25qvY3agm9OoRfb3x51TFuYmhMrH7sLwbcDKPPR4mVkUGlCBOgfKfQ2KpxtKeaQXLXplgrRRvaUYkq+9cYUSHaFY=,iv:aBMFg2t0IUQVuyvJp40xLQYlkBRr+6CZkN78Mo36QdI=,tag:MZbl24l4Zgs9Xm7zK2kC6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
