apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cS62l8D3C25j6B5ivjCJWmF8Qw5FmnuSTDIH6ysMNWo/OPVw6/N8vBVd189I4F0trm3ZOaa0x/egiygnO978EC5RkRs0Dyc6uxmDs5T0QDrPfpZ8OqhqvGCyI7/3M7V5O5eaQRuRmVTUE+kTzBMCgDsvSGMbqZNWaev4H5u1dBxoP/IK2KLw4PsHMx4ABI51w/PyGOBa0CYV26hmN/0ELMsXKQtUD/eLeGq5v4ALczNtXyGgjQkxndLJ70LOqildo4XcjCMjlU2fE9SNHPpSSrvuqnYby/SgpJaLD6QIpsScBm6ynHBNL6Ob2X8=,iv:3ytU+kuUU7cUUpv/DwGmiQepou0BF02hhw4qSXM8b8w=,tag:hIQmePROmw8a+QAsI4a9iw==,type:str]
kind: Secret
metadata:
    name: forgejo-cloudflared-creds
sops:
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOTc4aW1Oc0F4TlFvZzEx
            bUNTR2ZMcXlrdTR2c0hXYUtzQUdwamUxZ1FNClk5T015WGg2bFhnby9ONENXK3A2
            QmZWOURad2JBTU53MHVNczVYandBZWsKLS0tIFRZVDNLK1g5Y09wcTJrdzZOamlS
            SmI4YkxsdjhhRWdIZzVVcDFTTVZvdjgKM2ETpb4h1uOIIdV3SCnD15VDkR+PWeLo
            krYYgj0gpEn3GZ7kxmjbWzRyVGFNFIoTuoAASdHnQX/74ZeqaVOdyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T02:34:43Z"
    mac: ENC[AES256_GCM,data:/FtWalGNTIb9jWUGSqvo9+wJfaeee+Gie3etuP9SIJSy6fcubiG1cKp4haxCRSfzawSQuC/ywduLXOYkBZUUipCJEAqLYevTQYug3/1vrPA+p1wYcCGAXtiipaJzgKwf0YKA+DtjKR69BbOjk75ibBXl+CfHLmnuiAA2Z2DvE14=,iv:M44DPEOcE8x8SDt6w/AENbR95+baRuHGjUKlHoXVPcc=,tag:QbKFh7u8iLNx3U3BbSFf5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
