apiVersion: v1
data:
    FORGEJO__database__PASSWD: ENC[AES256_GCM,data:wznPsn3SY7Jf73yCii7ozxzaob+vvtIDmIcFlA8GN4O7sn9O8qtYJPA7DzA+dfBJ+grIOBm1TxPURVq2muS+GmFoA4DJRqVPqahOeRqMbHzuyLwywbMiJw==,iv:E6sVUCGH8v87Szaf97PnGf9/qRdTZpURic5erpbybIo=,tag:7yzZuo0mGi7hrdHazOBe1A==,type:str]
    FORGEJO__database__USER: ENC[AES256_GCM,data:KVICxQ==,iv:svaaWwDYnql2rcG5AUTwHJStQhGSnPBFzFBhOWyt+b0=,tag:UqxtXkjRLXvwaRw1jDnqyA==,type:str]
kind: Secret
metadata:
    name: forgejo-container-env
sops:
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSG5sMVY3V2Qrd0tNZG9w
            MDQ1YmQ4emxPczloL1BSVEhMcHpHUkhlL3hzCnhZTVhxWG5HTFpFL1pkbWllajZD
            QkdxdUY1aEJtWlBXMlhGVjZkK25oVlEKLS0tICt4bmVBTzBQdDZGY0FDODlVODZB
            MWR6UEpXbDVMU2RoQUxWUkdKZ0x0OWcKSZKH4zQRWwmD20fCZJ4NLsUZOgpx79sv
            1eEjvbq6vCTzlDPBtVq5yateDeSpsR4Vv4GaJBslBwAmNPIya1klKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:04:43Z"
    mac: ENC[AES256_GCM,data:DvArBDHmu8Qdt7R8fFBB2Js1j8Yadlghcj3g396TjEkCTw4+rxQlDBGYkq9e94y5/9Smw4kx4hf49KXK7Kyp4KePIFdAKng37tO0OL8jWk0BkiSCfZ3ZQF2fND7aVyCawtAE7f716JwDJ3KNK4Ao3ooi9l5j/IvHqtARWZT9FTQ=,iv:i9OynCCTnFr2EsfrjC6Rh52mCQgLgae2vJbFTR5hJhw=,tag:J3lW6+dQ+i55pXMzc1lNzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
