apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - forgejo-container-env-secret.yaml
  - forgejo-configmap.yaml
  - cloudflared-configmap.yaml
  - cloudflared-deployment.yaml
  - cloudflared-creds-secret.yaml
  - ../../base/forgejo/
