apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:m31dRg==,iv:TW1BXAlVtH3lKoxBhT8fCoSlW4BA6Ahx1MLGcaUwKRk=,tag:2aOjWeOKuhTIgW4fWaHXJA==,type:str]
    admin-password: ENC[AES256_GCM,data:rV5/u75zMLRXv+c3mhn578s4UVzEpADT,iv:O1t51/GFAL1FM5adQJTpOcGB20qVt1upd6JAknFbJUA=,tag:PkpQOx8zuIyhJwGAMKw26w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVGl0cldnZW9rdFpVajBO
            V3hFNEZKdmtLZjlpSGM4Wk9HQ1ljU3ZzMURrClRLUzZpdDczeXpRV0Q5djBvQTly
            M0NKaEZYbjh1bUFwTTE2UU9LQTdnSWMKLS0tIDVpODNBSnVzQzg5Z3N1YW14cGo2
            RkMxd0EvNk41NWk2TkpYVkM5MkdSQVkKa/tTcLxVI5uApEXeUV9y86yRPwvRg64k
            xZAs/D4ZKKIk9UaupMyzsu7SL+OaZTBVC7PxJK2JAhS2YCTby8kp8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T18:54:12Z"
    mac: ENC[AES256_GCM,data:nOQe7CXwd3l3WEryavCGgFbSwHLl3ml+tnBliB+xhhSr/sZql7ZZDg+RWqHh8Rzgbbxq4AyepuAx/7BhbMmZnH632JOBxWc7Xt5oENiYwVExCRuU4ZMsttVM6eNUZ3jt4kj0ThT/jMAZYvimrAYC0RIloD8609HHkgeUMshuous=,iv:EQVbpdjMru6rEk8r3NDqS/372InlgoPmzfOQzmSgvA8=,tag:z0d/9joot3Souir6MOQ/iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
