apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: forgejo-db-production-scheduled-backup
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: forgejo-db-production-cnpg
