apiVersion: v1
data:
    password: ENC[AES256_GCM,data:5ihLcUm2Gnp2irFpoAQR6KvGBI3iWF8aXDHAmQM8KkiVdFngillVXEMm9VU5Gy98eUqxv5E8voBMCzKuaEdcyIU0NA4ymE7LIb3lhUG83vNWRNcFacqvEg==,iv:ael4i1cGnRwngUvbDQKZZPsVUwQ4nzkTQhw4rKGyKg0=,tag:z+vxzFo8gNABuk9Y5Wvj7Q==,type:str]
    username: ENC[AES256_GCM,data:x65Hlg==,iv:VwycfeXUpkp2muDAcaC2TMktWZ7hiKPbMFAcPvG8XXM=,tag:fz1JF4lE+W21ZS7BEtGjrA==,type:str]
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: forgejo-db-creds
sops:
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcTRHMTVXVXAzbW1EQUha
            UlM2bk9YdzJWMnkrMzNtbVpOYmd5VGozVWxrClVKRXhXN3VOeHpDWlJ0UXA0anE4
            TGJGVnBFcXZldG8yeUVTRFBwRWNrUXcKLS0tIENPeFZOdHRNbXVSV3FVc0NRVmJ0
            WjJrZENOWnc2Sit0d0NZdXloc0pYTUUKx2HcOr54Fm22QZpNfcRclgDwayAfJ/1U
            3+rMTfipckNDgUs+ZBrmL0JThEY0R5vjouKqrtFMgG9E86OP5Zx3HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:01:25Z"
    mac: ENC[AES256_GCM,data:gDTBLFOo1A9IIuWnmrN6qezGqfyMCAMtVgJmnwe7VLIpSsSY1x8ZwN0gwZdvpT4t+ZgQ80YMHfQvEOQ8GDNzNwRbSu7IVQrJkCjOEENcNQmydmlGksCPYfL+9f9y0yO9oMAjNw0V0ZBkDyEhPjsW93dIAo68PmGhtlxWn8XbCho=,iv:WjpUjoxdwyX2KBcvwIVdX1gC2O2iuBDug+1K53zj8lE=,tag:/+Z33ROrvcWUhnOdnAouiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    ACCESS_KEY: ENC[AES256_GCM,data:CBSzn4zYR7gV2TzLYdc6fHnG6lTOapTW/vuptp5EXDi+kTh8szjR0S6pI/U=,iv:kX1BX2ms4h9iFS7okJXmfUrSK2P8P6GEMgT1EE0Lnrc=,tag:RxtzJmjCzM40/dcG7oiP0Q==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:Jo5DSDnOJUnx6NHptjzcgpTKn7W9U45Ut6xycdfDIju8Nve8FbuLxWih7pLyHKgrNt79UXCzWy4vxIr3yK3f6WfPNajnFM9l2QWeYAymCbBwMSivM/ZTWg==,iv:LcutDlhUXDqbdM6r/rD4yHoDjtuUcFfDpt360Mwy7Uw=,tag:/RkNv4EFH24yZNzpNJoO8w==,type:str]
kind: Secret
metadata:
    name: forgejo-db-production-backup-s3-key
sops:
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcTRHMTVXVXAzbW1EQUha
            UlM2bk9YdzJWMnkrMzNtbVpOYmd5VGozVWxrClVKRXhXN3VOeHpDWlJ0UXA0anE4
            TGJGVnBFcXZldG8yeUVTRFBwRWNrUXcKLS0tIENPeFZOdHRNbXVSV3FVc0NRVmJ0
            WjJrZENOWnc2Sit0d0NZdXloc0pYTUUKx2HcOr54Fm22QZpNfcRclgDwayAfJ/1U
            3+rMTfipckNDgUs+ZBrmL0JThEY0R5vjouKqrtFMgG9E86OP5Zx3HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T03:01:25Z"
    mac: ENC[AES256_GCM,data:gDTBLFOo1A9IIuWnmrN6qezGqfyMCAMtVgJmnwe7VLIpSsSY1x8ZwN0gwZdvpT4t+ZgQ80YMHfQvEOQ8GDNzNwRbSu7IVQrJkCjOEENcNQmydmlGksCPYfL+9f9y0yO9oMAjNw0V0ZBkDyEhPjsW93dIAo68PmGhtlxWn8XbCho=,iv:WjpUjoxdwyX2KBcvwIVdX1gC2O2iuBDug+1K53zj8lE=,tag:/+Z33ROrvcWUhnOdnAouiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
