apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: |
    tunnel: passbolt
    credentials-file: /etc/cloudflared/creds/credentials.json

    no-autoupdate: true
    ingress:
    - hostname: passbolt.eniohomelab.com
      service: http://passbolt:80
    - service: http_status:404