apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passbolt
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: "passbolt.eniohomelab.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: passbolt
            port:
              number: 80
  tls:
    - hosts:
        - "passbolt.eniohomelab.com"
      secretName: passbolt-certificate-tls