apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:latest
        ports:
        - containerPort: 13378
        volumeMounts:
        - name: audiobooks
          mountPath: /audiobooks
        - name: podcasts
          mountPath: /podcasts
      volumes:
      - name: audiobooks
        hostPath:
          path: /mnt/eniostorage/gio/audiobooks
      - name: podcasts
        hostPath:
          path: /mnt/eniostorage/gio/podcasts