apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: audiobooks
          mountPath: /audiobooks
        - name: podcasts
          mountPath: /podcasts
        - name: config
          mountPath: /config
        - name: metadata
          mountPath: /metadata
      volumes:
      - name: audiobooks
        persistentVolumeClaim:
          claimName: audiobookshelf-audiobooks
      - name: podcasts
        persistentVolumeClaim:
          claimName: audiobookshelf-podcasts
      - name: config
        persistentVolumeClaim:
          claimName: audiobookshelf-config
      - name: metadata
        persistentVolumeClaim:
          claimName: audiobookshelf-metadata
