apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-configmap
data:
  config.yaml: |
    tunnel: audiobookshelf
    credentials-file: /etc/cloudflared/creds/credentials.json

    no-autoupdate: true
    ingress:
    - hostname: audiobookshelf.eniohomelab.com
      service: http://audiobookshelf:80
    - service: http_status:404