apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-production-cnpg
spec:
  description: Postgres cluster for the linkding application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 1

  storage:
    size: 1Gi

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r