apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-db-production-cnpg
spec:
  description: Postgres cluster for the linkding application
  imageName: quay.io/enterprisedb/postgresql:16.1
  instances: 1

  inheritedMetadata:
    labels:
      app: linkding-database
      policy-type: "database"

  env:
    - name: POSTGRES_DB
      value: linkding

  storage:
    size: 1Gi

  # bootstrap:
  #   recovery:
  #     source: linkding-db-production-cluster-backup
  #     database: linkding
  #     owner: linkding
  #     secret:
  #       name: linkding-db-creds

  externalClusters:
    - name: linkding-db-production-cluster-backup
      barmanObjectStore:
        destinationPath: "https://164d89d21e40fc0dca2adff949fe6905.r2.cloudflarestorage.com/linkding"
        s3Credentials:
          accessKeyId:
            name: linkding-db-production-backup-s3-key
            key: ACCESS_KEY
          secretAccessKey:
            name: linkding-db-production-backup-s3-key
            key: SECRET_KEY
  backup:
    barmanObjectStore:
      destinationPath: "https://164d89d21e40fc0dca2adff949fe6905.r2.cloudflarestorage.com/linkding"
      s3Credentials:
        accessKeyId:
          name: linkding-db-production-backup-s3-key
          key: ACCESS_KEY
        secretAccessKey:
          name: linkding-db-production-backup-s3-key
          key: SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  managed:
    services:
      disabledDefaultServices:
        - ro
        - r