apiVersion: v1
data:
    ACCESS_KEY: ENC[AES256_GCM,data:TgsPOGKnnQ8GLJ1+dO4qQpZlNI3sPIFJQbVss9bn5Yt/x0wJMQyCSjI5TLo=,iv:DTNflNZCXRlrFcyMpFnFYGgzWhq/r2xd7w8MvOeAf9Q=,tag:BLbFDXvE2Buy0y8HRmttwQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:09mPO/AmAr/wGb++GZu1OtvmoVxLekhlWfj+5UpHy/OZOIEus/IVF4KlL0Hs1NqbzcpWUlVYXyCJBcnoAJy5zal1Wn5xWm7UmxkCuMd5UsKzu2FvIBqDrg==,iv:CI1anniJ2moMnlHccajAPejVHFYpDib7UI+G3huitrk=,tag:R72tSKldKrh1oDDZxYGYuQ==,type:str]
kind: Secret
metadata:
    name: linkding-db-production-backup-s3-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdWhwblBBRFNJbm0vVkdK
            ck1vWENKYjdvTnFkcDNIVEpWOUdCVnNMSHg4CkkrTWIwSDdnOEsvbHBGTXgrL05v
            aVZTWW9OVWRXdzN5L1VwVzZYS01kNGMKLS0tIGJHU0xyZVJURUVidGxoRVBpRWN6
            K2FGVDNrTkZ2aE5FeGtCQkxOeEJrZ0kK50hjNLXPjoJUTa8Ei322vO95MPQfcJxc
            P/y0v+mzHfrZWZhawW4Ei+N6LgDfqFy4F2hEMWy2sLC8/K6skvgA5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T19:03:44Z"
    mac: ENC[AES256_GCM,data:2unjUFnx8MT/zAV0z0qMp5y8GGbj2jWo4EnwxYKLLEtfwQHwqG1zRaPorpg/Ksk7dPqP5DwcH6OexnDH0ckPixaCuLnMjSdOua9cTgwEIBJOpUa8ilZ1QHnc8FkKaPyTJwHSJF5mQrEuUTRFs5NX3rXGkESLBRVDQn1kHUQxr8c=,iv:VZjY3u49kG5LJtmxJ7bwAset8MbQby58UU5Ffa3Z8nE=,tag:VTnVAcKd8N5IYJFeLJR7Tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:flx2z2IPC516LbOOzflT1vh1oH4IB5vF2f1E1OTBmCHPzUM3LiTjuQDf/Yq31LFO/m+5OKkydybZb1gtv8fsK7ipm2PjbKVBAZOTSqvd8Ggq3x5XhBbrDg==,iv:gZMIEwuySUBmMiE/hx+SYtH5x3rcDJFj3hWMSzGxNfo=,tag:IslVC3N0Ni1H1drOJmL8mA==,type:str]
    username: ENC[AES256_GCM,data:D16llQ==,iv:D5h3wo8rB68XCQoME/qWjQNnMMpIYznOEzF/Oon0XNE=,tag:JM2zublhBg3c90onn9tNxw==,type:str]
kind: Secret
metadata:
    name: linkding-db-creds
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdWhwblBBRFNJbm0vVkdK
            ck1vWENKYjdvTnFkcDNIVEpWOUdCVnNMSHg4CkkrTWIwSDdnOEsvbHBGTXgrL05v
            aVZTWW9OVWRXdzN5L1VwVzZYS01kNGMKLS0tIGJHU0xyZVJURUVidGxoRVBpRWN6
            K2FGVDNrTkZ2aE5FeGtCQkxOeEJrZ0kK50hjNLXPjoJUTa8Ei322vO95MPQfcJxc
            P/y0v+mzHfrZWZhawW4Ei+N6LgDfqFy4F2hEMWy2sLC8/K6skvgA5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T19:03:44Z"
    mac: ENC[AES256_GCM,data:2unjUFnx8MT/zAV0z0qMp5y8GGbj2jWo4EnwxYKLLEtfwQHwqG1zRaPorpg/Ksk7dPqP5DwcH6OexnDH0ckPixaCuLnMjSdOua9cTgwEIBJOpUa8ilZ1QHnc8FkKaPyTJwHSJF5mQrEuUTRFs5NX3rXGkESLBRVDQn1kHUQxr8c=,iv:VZjY3u49kG5LJtmxJ7bwAset8MbQby58UU5Ffa3Z8nE=,tag:VTnVAcKd8N5IYJFeLJR7Tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
