apiVersion: v1
data:
    ACCESS_KEY: ENC[AES256_GCM,data:e6R6Y2ctECqspzz/AT1Tv3F4u1oEdZZ7YspdJg1eNA4PmI/RqP88OlOOtdw=,iv:sNa3nIcRA8Pq7DuFgqf444r1ZK7kLUD298Ha6G3pOoI=,tag:Dp9V0LIZx1UiMcQTOFeQ0w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:xN4jLNM+w1mMUl7Hg6PftIycYPALHNqS2+6SFnh3UrwivGSaXeHSMEJ8bCJmrvQEw7EYK82GKRED1C8p9ZRFR2j/Fo0QkCcg4zc0iQoTOH4yZ6Ero2FOLg==,iv:mgFB6+IGDffni43yCg13VtbvjtROACyao9bVK5gstx4=,tag:rZaK0lsy3WqMQdV84c38gA==,type:str]
kind: Secret
metadata:
    name: linkding-db-production-backup-s3-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRWtWTEE1YjJWLzNGSHg1
            ek42UFFHQkF4NDRObWRXMXNTTUFyc2Z2cDFvClovRTJaNkxQTTRjU1UrTWZuY0gv
            L2RTNk9hMTNmZEF6dC9LK1ZncjZuWjQKLS0tIEYzUVZ1dUVUckFNTkFreGNIcmRs
            dTZuSTZKK1BoWWhyaFRId3A3OGkxUk0K97+qPtYYqofhncm6B5G4U6xOjS+oVrO/
            NGCzOQpqiiALvyvn4AHg4HZ+pqBNLJlilvxcJzh5SBxN+8OeWhBGqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T04:47:42Z"
    mac: ENC[AES256_GCM,data:uaIcPOpKn2FfuD1ouHq63B98hQ05DDC1KT85k8a8d7Ztgw7XUZWSueWfM+KdBwRzffgfat399dQqICuyzTyGbDuGqxH2pTs1CudPxyG3CkVBmqBLpln10WfyBMPNH7G84N7PmGbwNEbeS3jIo7vQr9yldIV/7EOSeq5qCeL2LX0=,iv:X9Oel8UmffBgTm3q8fU9qGqo8oR0BQ/cVZ595AxsA2Q=,tag:CdWmedh4AJuRgqT/LraYeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:l89ADqUrqUJ/Eqf92xYySCYOJxNBETpOnTk4Wrrd1gWx5M++HgLdVCTIBnc/B46Uub6T7QSGi8ek4y8PD3+UL0bo7v8/AUz5Kf8q7txlmjqcB4Tj61XWnA==,iv:wmYEqbFlbt/No+QDrt4WPt0SYS0m+cIoBMTTBPU/BYY=,tag:mFIzD6Sl8JcXEK6qjhW0UQ==,type:str]
    username: ENC[AES256_GCM,data:lcEfzg==,iv:xpx8vFW6Svv8GpGfjmREBj25QT/O/YLInDCU3qidzcs=,tag:4kUypEUPLVqc858OfzpI6Q==,type:str]
kind: Secret
metadata:
    name: linkding-db-creds
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRWtWTEE1YjJWLzNGSHg1
            ek42UFFHQkF4NDRObWRXMXNTTUFyc2Z2cDFvClovRTJaNkxQTTRjU1UrTWZuY0gv
            L2RTNk9hMTNmZEF6dC9LK1ZncjZuWjQKLS0tIEYzUVZ1dUVUckFNTkFreGNIcmRs
            dTZuSTZKK1BoWWhyaFRId3A3OGkxUk0K97+qPtYYqofhncm6B5G4U6xOjS+oVrO/
            NGCzOQpqiiALvyvn4AHg4HZ+pqBNLJlilvxcJzh5SBxN+8OeWhBGqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T04:47:42Z"
    mac: ENC[AES256_GCM,data:uaIcPOpKn2FfuD1ouHq63B98hQ05DDC1KT85k8a8d7Ztgw7XUZWSueWfM+KdBwRzffgfat399dQqICuyzTyGbDuGqxH2pTs1CudPxyG3CkVBmqBLpln10WfyBMPNH7G84N7PmGbwNEbeS3jIo7vQr9yldIV/7EOSeq5qCeL2LX0=,iv:X9Oel8UmffBgTm3q8fU9qGqo8oR0BQ/cVZ595AxsA2Q=,tag:CdWmedh4AJuRgqT/LraYeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
