apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloudflared-creds
stringData:
    credentials.json: ENC[AES256_GCM,data:tkSYpCMq8ksTlv6k/S3PdfqS7gxSK9WJol/v0nrNVPpMkMQu8xWpUJKX0QqdBE+OeQ+mKSMcD4REdlJx0K+yD0mYEEp94M1lC2y8ONGFUkdZ6i7HlPaiR0iUFuZ8O/DvUYCGXEGxYqJIaI30x1JJLxhYvyaFqExBD/hektzwLa40CFE/uOinSOXl6fPNH5KwFGa3gCm9Y9y7pV0rtMkSH7QnY99g3lNUd9HZdmqLZA==,iv:lnW9nx+/SLTfKNoIMN/F4ZXuxtss9fuIdI1p6o5ZUHo=,tag:mmpAA9NaY//dJKQDQjdg6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bk1ZSHZQN0FHRXBxVFd5
            Slpac1JXZjkzb1JuajNQRlZNMUdiSWlpQlVFClpxbjdaTlU0cjZuTmtNaEJEWDdI
            azN1a0hnd2x3SlpMcDFzNzZ4TGt2RGMKLS0tIE5LVU84dlBybmN5c2JKR3MxaUNX
            aTI2RHdPa2p3dUZhSm5yRXdrSG9nWDQKVEqHvWSckzRorRC7YVWaxGtBkcqSok4B
            zTYwMu8wLI0BnoCz2LNBUUUM9bKow8fKrKSdDx2NSArraxhJNvAj1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T18:54:58Z"
    mac: ENC[AES256_GCM,data:LZEOZqKfS7XjpOtjJGx8TAPMFlj9U/W1HxPlhuj3WaTrJeXZVDi251t9saKsv3z/QcNyoePWpXLiNgaLpga1Crm6c0IlUni748v/B0mLo2/saBy3zf6RY+xRB+y2QzsN1nG03gLm3tMNSDbhuV45f+B4y6vEsg3xwdzw/Iz1YcM=,iv:mf2RGnU1xJ54ZtsCSYPKxJS6A382kU8qlTYZoFubFu8=,tag:b1/yfldocGc9bESyBbN4ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
