apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
        policy-type: "app"
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:13
          envFrom:
            - configMapRef:
              name: forgejo-configmap
            - secretRef:
              name: forgejo-container-env
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
          ports:
            - containerPort: 3000
              protocol: TCP
            volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
