apiVersion: apps/v1
kind: Deployment
metadata:
  name: passbolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passbolt
  template:
    metadata:
      labels:
        app: passbolt
        policy-type: "app"
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
        - name: passbolt
          image: passbolt/passbolt:latest-ce-non-root
          envFrom:
            - configMapRef:
                name: passbolt-configmap
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: passbolt-gpg-data
              mountPath: /etc/passbolt/gpg
            - name: passbolt-jwt-data
              mountPath: /etc/passbolt/jwt
      volumes:
        - name: passbolt-gpg-data
          persistentVolumeClaim:
            claimName: passbolt-gpg-data
        - name: passbolt-jwt-data
          persistentVolumeClaim:
            claimName: passbolt-jwt-data