apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passbolt-gpg-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: passbolt-jwt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi