apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:58HYQ8EzoAePNOsAbIWKnPEBz9gUWNGJv3T0eMWLIeYmiUYyNwTZcY6+HSecpLKTS1vgUhp/3CnExZz63mdi7X6rpHBRkbFv3bTAvx1J6NV30fje2KI667Wnjcz6B/xBznxQzHjoWwibA+qIcbg24ZnpU4kIRg3R8GTIBd7sT8Pi0asOzq+TmDPVA+HQJPNKOTPLeF/jDumOEMsrIkVFSPPT0Pv/RqBXSMoza3ONsBIVYNOJ+31wMA8txGwIj92frUPuwWLpLcVdsysR30QTnQgHO9o30I8wERS4TVCpNokJaZzz++lH0hI1MrI=,iv:PM6GBnJwApF75cCacTIZHIl4LJNsWTYLUxw5+aMk0v4=,tag:jGeuRlFTWtSWItWtdvBi/A==,type:str]
kind: Secret
metadata:
    name: kavita-cloudflared-creds
sops:
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT3lLcUxiVmZCMExrT3c0
            ZEI1aUF2MHBiMWN0ZVd2bGUvVW94N0M3Wno0CmU4aGNoN2lmWHk2RUt1UjV5OVV6
            WDZKejkxVnRYek9xNWlKUHJNYlkrOFUKLS0tIFM0OHFvWWVpblAxRVM0MlRkL0F6
            WkFGdWhtRWVObGtBK0tJdTZFekFabGsKaArYZhk/lQqWLlNJaYd+teAraNk3FL7j
            csJ/+JS2yE+E7rM8bu7r8Pk6kIB5f9QQ/3CsQ3A5fuJcMjkavJlP5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T15:06:07Z"
    mac: ENC[AES256_GCM,data:R2/+XULcLPeNsRQvPX4vaHeLvaOiaeARg5nrxA3KJIsa+SfmNo/a4ZV8fH47p+34KCrm8TgKdaAYsmRC8dpblcWNhXJPnH22R5aek3l0j+vrrSoNniIPwF+RzSV/X30zKVvGZXby0DtQ6RN3/V1fWCgToh6wuWCQf15cTDvwXZI=,iv:cqeJs/WBmj3PmpYS65VKCvtIuy+A6U3wAHXFCn3odf0=,tag:EQgEqq4K0W8sdaNra3J1eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
