apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: media
          mountPath: /media
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        env:
        - name: JELLYFIN_DATA_DIR
          value: /data
        - name: JELLYFIN_CONFIG_DIR
          value: /config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: jellyfin-media
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: data
        persistentVolumeClaim:
          claimName: jellyfin-data
