apiVersion: v1
data:
    LIVEBOOK_COOKIE: ENC[AES256_GCM,data:ZhU1zZ5tNpYV1a+Mqdw6dEjtqsPBn+/yti3BIm7Tm6CZs4b90MT/L1QTMUOv5V4odj3TofEiNcA=,iv:/whpUlNmzBVjqKVMzIPe/Vh9UYoPKf5nH6bsRxerruY=,tag:0k9mAZmXXh1IrRI/Eu+BTg==,type:str]
    LIVEBOOK_PASSWORD: ENC[AES256_GCM,data:voICKkthsFpMK5Fz8s+Bv/xO8IUKMO/rW2hgK9qwKEs=,iv:h0UVA462tuG2rVH+S+1GJylP65OJxSM2LaSKuTlyCGg=,tag:qF83s/BNAAgr0sP4YUFpxw==,type:str]
    LIVEBOOK_SECRET_KEY_BASE: ENC[AES256_GCM,data:jNo8W10DaEjj9bjeZ2LE5IQxtQWDdRhmpV+chLg0a71vP4WRoIkELKCnUMiHkuCc7hcNQPxbtifb8M3RlNPc3lABR6RjVFQR/8mFyOFyzKESrr26+qyDsQ==,iv:eZL1WIa0ETEXVNcl99vpWtM0tFYLY2JibFQpAnqh4/A=,tag:jqpGWMXR7UEJ9U5+2xyVlQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: livebook-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jredhcrn9gsyckesgwaat8f4rgcsl279v8ydsde3ucehzlez5vas0xc9n7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZjRXMGlSMDF6RmRvU0Fr
            ZGFjZkpNSHQ4NXFmTS9JSzVyb3c2OFJJcFhNCkR6bk1QZ0QzMkpUUW1Wanl4NXhT
            My9OZUlvTlJscG5KVzQ4b2JOL2NQcjgKLS0tIDFOdmUzeVJ6dXlocHk3TkgwUVdQ
            OEt4VU1MNlNQM0hNMzcwakVOeUNtNU0KIYwRWTEkb3xg9jZ+bipHMNaVm7pv+/YL
            xzY2wN41HhduZaT+DyvHXNdNbc1lJn/h+/T+cdOGzcPJURc370SjPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T15:49:08Z"
    mac: ENC[AES256_GCM,data:quWmsWiOGH55fXhEuN1BcoiYgAMJXQn0mYgK9RPYXKtkUyYg4zQRz/oE50kbGIyEdFdrCXVzi1QzTyWhMmgG3/zEzdIdrtsStMMJo+zpvLD9uRK9xOMFLmPTsr0GxNPP5NsZYbEhEOLlWOvny7ULefDH2LO0SxZ0KIkTT+nC/zo=,iv:kFEO9PK8/5uHXYv0tYhKh5UQ/9C+jFunn/DwAw9VXNU=,tag:9nW7G7EaI/0iBV1b6Wr59w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.9.4
