apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: triliumnext/notes:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trilium-data
              mountPath: /home/trilium/trilium-data
      volumes:
        - name: trilium-data
          persistentVolumeClaim:
            claimName: trilium-data