apiVersion: apps/v1
kind: Deployment
metadata:
  name: obsidian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obsidian
  template:
    metadata:
      labels:
        app: obsidian
    spec:
      containers:
      - name: obsidian
        image: lscr.io/linuxserver/obsidian:latest 
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Sao_Paulo"
        ports:
          - containerPort: 3000
        volumeMounts:
        - name: obsidian
          mountPath: /config
      volumes:
      - name: obsidian
        hostPath:
          path: /mnt/eniostorage/gio/eniobackups/obsidian