apiVersion: v1
kind: Service
metadata:
  name: livebook
spec:
  type: LoadBalancer
  selector:
    app: livebook
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
    - protocol: TCP
      port: 3003
      targetPort: 3003