apiVersion: v1
kind: Service
metadata:
  name: livebook
spec:
  type: ClusterIP
  selector:
    app: livebook
  ports:
    - protocol: TCP
      port: 80
      name: app
    - protocol: TCP
      port: 81
      name: iframe